/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubedb.client.models.ComGithubAppscodeKubeMonApiPrometheusSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComGithubAppscodeKubeMonApiAgentSpec
 */

public class ComGithubAppscodeKubeMonApiAgentSpec {
  @SerializedName("agent")
  private String agent = null;

  @SerializedName("prometheus")
  private ComGithubAppscodeKubeMonApiPrometheusSpec prometheus = null;

  public ComGithubAppscodeKubeMonApiAgentSpec agent(String agent) {
    this.agent = agent;
    return this;
  }

   /**
   * Valid values: coreos-prometheus-operator
   * @return agent
  **/
  @ApiModelProperty(value = "Valid values: coreos-prometheus-operator")
  public String getAgent() {
    return agent;
  }

  public void setAgent(String agent) {
    this.agent = agent;
  }

  public ComGithubAppscodeKubeMonApiAgentSpec prometheus(ComGithubAppscodeKubeMonApiPrometheusSpec prometheus) {
    this.prometheus = prometheus;
    return this;
  }

   /**
   * Get prometheus
   * @return prometheus
  **/
  @ApiModelProperty(value = "")
  public ComGithubAppscodeKubeMonApiPrometheusSpec getPrometheus() {
    return prometheus;
  }

  public void setPrometheus(ComGithubAppscodeKubeMonApiPrometheusSpec prometheus) {
    this.prometheus = prometheus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubAppscodeKubeMonApiAgentSpec comGithubAppscodeKubeMonApiAgentSpec = (ComGithubAppscodeKubeMonApiAgentSpec) o;
    return Objects.equals(this.agent, comGithubAppscodeKubeMonApiAgentSpec.agent) &&
        Objects.equals(this.prometheus, comGithubAppscodeKubeMonApiAgentSpec.prometheus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agent, prometheus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubAppscodeKubeMonApiAgentSpec {\n");
    
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    prometheus: ").append(toIndentedString(prometheus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

