/*
 * KubeDB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * Contact: hello@appscode.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kubedb.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kubedb.client.models.V1alpha1Origin;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1alpha1DormantDatabaseSpec
 */

public class V1alpha1DormantDatabaseSpec {
  @SerializedName("origin")
  private V1alpha1Origin origin = null;

  @SerializedName("wipeOut")
  private Boolean wipeOut = null;

  public V1alpha1DormantDatabaseSpec origin(V1alpha1Origin origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Origin to store original database information
   * @return origin
  **/
  @ApiModelProperty(required = true, value = "Origin to store original database information")
  public V1alpha1Origin getOrigin() {
    return origin;
  }

  public void setOrigin(V1alpha1Origin origin) {
    this.origin = origin;
  }

  public V1alpha1DormantDatabaseSpec wipeOut(Boolean wipeOut) {
    this.wipeOut = wipeOut;
    return this;
  }

   /**
   * If true, invoke wipe out operation
   * @return wipeOut
  **/
  @ApiModelProperty(value = "If true, invoke wipe out operation")
  public Boolean isWipeOut() {
    return wipeOut;
  }

  public void setWipeOut(Boolean wipeOut) {
    this.wipeOut = wipeOut;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1DormantDatabaseSpec v1alpha1DormantDatabaseSpec = (V1alpha1DormantDatabaseSpec) o;
    return Objects.equals(this.origin, v1alpha1DormantDatabaseSpec.origin) &&
        Objects.equals(this.wipeOut, v1alpha1DormantDatabaseSpec.wipeOut);
  }

  @Override
  public int hashCode() {
    return Objects.hash(origin, wipeOut);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1DormantDatabaseSpec {\n");
    
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    wipeOut: ").append(toIndentedString(wipeOut)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

